puts ""
puts "--------------------------------------------"
puts ""
puts "To create the Following model please run:"
puts ""
puts "rails generate following"
puts ""
puts "--------------------------------------------"
puts ""